# Generated by Django 4.0.4 on 2022-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
